import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import SupabaseListener from "@/components/SupabaseListener"
import createServerClient from "@/lib/supabaseServer"
import Navbar from "@/components/CommonSection/Navbar"
import Header from "@/components/CommonSection/Header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export const revalidate = 0

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabaseClient = createServerClient()

  const {
    data: { session },
  } = await supabaseClient.auth.getSession()

  return (
    <html lang="en">
      <body>
        <SupabaseListener accessToken={session?.access_token || ""} />
        <nav>
          <Navbar />
        </nav>
        <header>
          <Header />
        </header>
        <main>
          <div className={inter.className}>{children}</div>
        </main>
      </body>
    </html>
  )
}
